name: Build and Deploy
on:
  push:
    branches: [ master ]
  schedule:
    - cron: '37 0 * * *'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        run: |
          sudo apt-get install openssh-client python3-setuptools

      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/checkout@v3
        with:
          repository: JinnLynn/genpac
          path: genpac

      - uses: actions/checkout@v3
        with:
          repository: gfwlist/gfwlist
          path: gfwlist

      - uses: petronny/git-config-user@master
        with:
          path: .

      - run: |
          cd genpac
          sed 's/from collections import Callable/from collections.abc import Callable/g' -i $(grep 'from collections import Callable' . -rIl)
          sudo python3 setup.py install

      - name: Update
        run: |
          set -x

          genpac --pac-proxy "SOCKS5 127.0.0.1:1080; SOCKS 127.0.0.1:1080; DIRECT;" --gfwlist-url - --gfwlist-local gfwlist/gfwlist.txt --user-rule-from=src/user-rule.txt -o dist/gfwlist.pac
          sed '1,7d' -i gfwlist.pac

      #          git add gfwlist.pac
      #          git commit -m "[$(LANG=C date)] auto update" || exit 0

      #          [ -n "${{ secrets.READ_ONLY }}" ] && git show && exit 0

      #          git push origin master

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: dist # The branch the action should deploy to.
          FOLDER: dist # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
